# DATASET FOR TRAINING

[general]
resolution = [1024, 1024]
caption_extension = ".txt"
batch_size = 36
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "/workspace/musubi-tuner/2_datasets/a1fa_b2c3d_1arge/data/image"
cache_directory = "/workspace/musubi-tuner/2_datasets/a1fa_b2c3d_1arge/data/cache"
num_repeats = 16

[[datasets]]
image_directory = "/workspace/musubi-tuner/2_datasets/a1fa_b2c3d_grad1ent/data/image"
cache_directory = "/workspace/musubi-tuner/2_datasets/a1fa_b2c3d_grad1ent/data/cache"
num_repeats = 12

[[datasets]]
image_directory = "/workspace/musubi-tuner/2_datasets/a1fa_k1ds_monos1ze/data/image"
cache_directory = "/workspace/musubi-tuner/2_datasets/a1fa_k1ds_monos1ze/data/cache"
num_repeats = 18

[[datasets]]
image_directory = "/workspace/musubi-tuner/2_datasets/a1fa_on1y_sma11/data/image"
cache_directory = "/workspace/musubi-tuner/2_datasets/a1fa_on1y_sma11/data/cache"
num_repeats = 15