# DATASET FOR VALIDATION

[general]
resolution = [1024, 1024]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "/workspace/musubi-tuner/2_datasets/a1fa_b2c3d_1arge/val/image"
cache_directory = "/workspace/musubi-tuner/2_datasets/a1fa_b2c3d_1arge/val/cache"
num_repeats = 1

[[datasets]]
image_directory = "/workspace/musubi-tuner/2_datasets/a1fa_b2c3d_grad1ent/val/image"
cache_directory = "/workspace/musubi-tuner/2_datasets/a1fa_b2c3d_grad1ent/val/cache"
num_repeats = 1

[[datasets]]
image_directory = "/workspace/musubi-tuner/2_datasets/a1fa_k1ds_monos1ze/val/image"
cache_directory = "/workspace/musubi-tuner/2_datasets/a1fa_k1ds_monos1ze/val/cache"
num_repeats = 1

[[datasets]]
image_directory = "/workspace/musubi-tuner/2_datasets/a1fa_on1y_sma11/val/image"
cache_directory = "/workspace/musubi-tuner/2_datasets/a1fa_on1y_sma11/val/cache"
num_repeats = 1